name: Dev

on:
#   push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.3.0
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install unrar
      - name: Set up Python
        uses: actions/setup-python@v3.1.4
        with:
          python-version: 3.10.11
          cache: "pip"
          cache-dependency-path: "py/requirements.txt"
      - name: Install Requirements
        run: |
          pip install -r requirements.txt
        working-directory: py
      - name: Update AssetBundles
        run: |
          python downloadAsset.py
        working-directory: py
#       - name: chmod download
#         run: chmod +x download.sh
#       - name: download
#         run:  ./download.sh
#       - name: chmod Build
#         run: chmod +x patch_bilibili.sh
#       - name: Build apk
#         run:  ./patch_bilibili.sh
#       - name: Zipalign chmod
#         run: chmod +x zipalign_sign.sh
#       - name: Zipalign and Sign Android release
#         run: ./zipalign_sign.sh

#       - uses: marvinpinto/action-automatic-releases@latest
#         with:
#           repo_token: "${{ secrets.GITHUB_TOKEN }}"
#           automatic_release_tag: "BILIBILI"
#           draft: true
#           title: " ${{ env.PERSEUS_VERSION }}"
#           files: |
#             build/*.apk
